local Cli = require "cosy.cli"

local cli = Cli.new ()
local ok = xpcall (function ()
  cli:start ()
end, function (err)
  print ("An error happened. Maybe the client was unable to download sources from " .. (cli.server or "no server") .. ".")
  local errorfile = os.tmpname ()
  local file      = io.open (errorfile, "w")
  file:write (tostring (err) .. "\n")
  file:write (debug.traceback () .. "\n")
  file:close ()
  print ("See error file " .. errorfile .. " for more information.")
  os.exit (1)
end)
